---
title: "Lab & Pt 1: Wrangling and visualizing spatial data"
author: "Nick McManus"
date: "2023-02-23"
output: html_document
---

```{r setup, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

library(tidyverse)
library(here)
library(broom)

library(sf)
library(tmap)
```


# Read in CA county outlines

```{r}
ca_counties_sf <- read_sf(here('data/ca_counties/CA_Counties_TIGER2016.shp'))

# keep only county names and area
ca_subset_sf <- ca_counties_sf %>% 
  janitor::clean_names() %>% 
  select(county_name = name,
         land_area = aland)

# EX: if you didn't care about geometry and want it gone
ca_subset_df <- ca_subset_sf %>% 
  as.data.frame() %>% 
  select(-geometry)
```


## Check and set the CRS

```{r}
ca_subset_sf %>% 
  st_crs()

ggplot() +
  geom_sf(data = ca_subset_sf, aes(fill = land_area),
          color = 'white', #color of outline
          size = 0.1) +  #width of line
  scale_fill_gradientn(colors = c('cyan', 'blue', 'purple')) +
  theme_void()
```


## Another dataset on an invaseive species
```{r}
sesbania_sf <- read_sf(here('data/red_sesbania/ds80.shp')) %>% 
  janitor::clean_names()

st_crs(sesbania_sf)
#EPSG 9001

sesbania_3857_sf <- st_transform(sesbania_sf, crs = st_crs(ca_subset_sf))

```


## Plot them together
```{r}
ggplot()+
  geom_sf(data = ca_subset_sf, fill = 'grey60', size = 0.1) +
  geom_sf(data = sesbania_3857_sf, size = 1, color = 'red')
```


```{r}
ca_sesb_sf <- ca_subset_sf %>% 
  st_join(sesbania_3857_sf)

sesb_counts_sf <- ca_sesb_sf %>% 
  group_by(county_name) %>% 
  #look in id column. If NA, then make it false (! inverts it)
  #and false is mathematically a 0.
  #Those that aren't NA are True (i.e. 1), so those get added up
  summarize(n_records = sum(!is.na(id)))
```

## Plot the results

Choropleth map

```{r}
ggplot(data = sesb_counts_sf %>% 
         mutate(n_records = ifelse(n_records == 0, NA, n_records))) +
  geom_sf(aes(fill = n_records), color = 'grey20', size = 0.1) +
  scale_fill_gradientn(colors = c('yellow', 'orange', 'red'), na.value = 'white') +
  theme_void()
```


## Plot just the points in Solano county

```{r}
solano_sesb_sf <- sesbania_3857_sf %>% 
  filter(county == 'Solano')

solano_sf <- ca_subset_sf %>% 
  filter(county_name == 'Solano')

ggplot() +
  geom_sf(data = solano_sf, color = 'black', size = 3) +
  geom_sf(data = solano_sesb_sf, color = 'red', size = 2, alpha = 0.4)
```


## Make an interactive map

```{r}
### set tmap interactive mode
tmap_mode('view')

tm_shape(ca_subset_sf) +
  tm_fill('land_area', palette = 'BuGn') +
  tm_shape(sesbania_3857_sf) +
  tm_dots()
```





















